import express from 'express';
import authentication from './authentication';
import users from './users';
import products from './products';
import categories from './categories';
import genres from './genres';
import news from './news';
import certificates from './certificates';
import reviews from './reviews';
import segments from './segments';
import repliesPost from './repliesPost';
import orders from './orders';
import commentPost from './commentPost';
import payment from './payment';
import openaiChatbox from './openaiChatbox';
const router = express.Router();

export default (): express.Router => {
  authentication(router);
  users(router);
  products(router);
  orders(router);
  categories(router);
  genres(router);
  news(router);
  certificates(router);
  reviews(router);
  repliesPost(router);
  segments(router);
  commentPost(router);
  payment(router);
  openaiChatbox(router);
  return router;
};
